### PR TITLE
applied energistics adjustment support AE2WT / mechanism update

### PR DESCRIPTION
**Pull request by vindocel**
added new AE2 guis changed folder name to ae2, added support for [AE2WT](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals)

### CODE REVIEW

**Comment by Jimmy-sheep** [comment]
I think the border line of energy, fluid, gases, infuse_type etc. in "mekanism\gui" folder is too dark, that make them looks just a lump of black thing.

**Comment by CyanideX** [comment]
Thank you for all the work you put into this! ❤️ I'll try to get around to reviewing and merging soon.

**Comment by vindocel** [comment]
> Thank you for all the work you put into this! ❤️ I'll try to get around to reviewing and merging soon.

You're welcome, it's a pleasure to be able to help a project that I love, thank you for creating something amazing❤️,

I optimized some languages, removing those that had not been modified and keeping only the modified ones to make it lighter, and I modified the ones that had changed.

**Comment by vindocel** [comment]
> I think the border line of energy, fluid, gases, infuse_type etc. in "mekanism\gui" folder is too dark, that make them looks just a lump of black thing. I suggest use gray color to distinguish(like the right part of picture).
> 
> slurries_compare

**Comment by vindocel** [comment]
> I think the border line of energy, fluid, gases, infuse_type etc. in "mekanism\gui" folder is too dark, that make them looks just a lump of black thing. I suggest use gray color to distinguish(like the right part of picture).
> 
> slurries_compare

I did a complete rework on the icons just waiting for approval
Captura de tela 2022-11-21 154336

**Comment by CyanideX** [comment]
I'm not sure about the soft look of the inner shadow with no offset for buttons. What about something darker like this?

image

**Comment by CyanideX** [comment]
I'm still not a fan of the **_poop_** icon. 😆 Feel free to make it look nicer.

**Comment by vindocel** [comment]
> I'm not sure about the soft look of the inner shadow with no offset for buttons. What about something darker like this?
> 
> image

done much smoother now integrated better now

**Comment by vindocel** [comment]
> Thank you for all the work you put into this! ❤️ I'll try to get around to reviewing and merging soon.

take a good look at the integrated dynamics port
Of the ones I made for myself, I liked the most perfect, well integrated, it took a lot of work when it came to coloring the TEXT, it was more than worth it

**Comment by vindocel** [comment]
ready mekanism is perfect now I'm going to sleep <3

**Comment by Jimmy-sheep** [comment]
> ready mekanism is perfect now I'm going to sleep <3

I love these changed of icons, those looks very nice now.
But the pictures in "gui/radial" did't load in game, so maybe need to move them to the right place.
Second part is...in my opinion I think the dump icon need to be more "looks" like a button, I recolor one below, but I'm not a artist , so it looks not great as your icons.☹
Anyway, I still want to say again these all looks so great.❤️

dump

**Comment by vindocel** [comment]
ok, could you tell me which machines you use "gui/radial" I tried to give a general look at the game to find any errors but I didn't see which machines you use could you let me know so I can relocate and see if it changed to know exactly where it is,

**Comment by Jimmy-sheep** [comment]
> ok, could you tell me which machines you use "gui/radial" I tried to give a general look at the game to find any errors but I didn't see which machines you use could you let me know so I can relocate and see if it changed to know exactly where it is,

These files are which you put in gui/radial folder
empty, empty_alt, rotate, speed_extreme, speed_super, speed_fast, wrench, speed_off, vein_normal, vein_extended

Actually those should directly put in gui folder and named as:
empty, empty_alt, rotate, disassembler_slow, disassembler_normal, disassembler_slow, wrench, void, disassembler_vein, disassembler_extended_vein

And here's the picture where they use, some of them might not use but I saw them in mod default texture folder.

螢幕擷取畫面 (6)
螢幕擷取畫面 (7)

**Comment by vindocel** [comment]
> > ok, could you tell me which machines you use "gui/radial" I tried to give a general look at the game to find any errors but I didn't see which machines you use could you let me know so I can relocate and see if it changed to know exactly where it is,
> 
> These files are which you put in gui/radial folder empty, empty_alt, rotate, speed_extreme, speed_super, speed_fast, wrench, speed_off, vein_normal, vein_extended
> 
> Actually those should directly put in gui folder and named as: empty, empty_alt, rotate, disassembler_slow, disassembler_normal, disassembler_slow, wrench, void, disassembler_vein, disassembler_extended_vein
> 
> And here's the picture where they use, some of them might not use but I saw them in mod default texture folder. (I'm don't know how to describe in English, so I screenshot) This screenshot is taken after I move the files, so it shows correctly.
> 
> 螢幕擷取畫面 (6) 螢幕擷取畫面 (7)

there was a mistake on your part, the icons that you showed in the image are already modified,

they are no longer in the ''\GUI'' folder now they are inside ''\gui\radial'' it was a modification of the mechanism itself

look at the image below, I put the original texture before the modification and the one after the icon modifications side by side, you can clearly see the darker color of the icons that I modified.
roda
I hope I managed to solve your doubts <3

**Comment by Jimmy-sheep** [comment]
> there was a mistake on your part, the icons that you showed in the image are already modified,

Oops sorry, I think it's my fault maybe because I forgot I was play in 1.18.2 version.
I don't have no more problem now thank you.

**Comment by vindocel** [comment]
> > houve um erro de sua parte, os ícones que você mostrou na imagem já estão modificados,
> 
> Ops desculpe, eu acho que é minha culpa talvez porque eu esqueci que estou jogando na versão 1.18.2. Eu não tenho mais nenhum problema agora obrigado.

I'm sorry, I reread your question then I noticed that you were in another version these modifications are based on the 1.19 version of the mekanism

more to solve this and just duplicate the files from /radial to /gui

I'll let @CyanideX decide whether or not it's worth adding this
maybe it adds the modified \radial icons inside the \gui only in version 1.18 down there in CurseForge

**Comment by CyanideX** [comment]
I wanted to merge this but GitHub said there were too many conflicts. Would have been ideal to separate each mod into a different PR instead of all of these changes. 😞 Any chance you'd like to resubmit?

(Also, sorry I've been away for so long. Life and work... overwhelming.)

**Pull request closed without merging**
